USE [master]
GO
/****** Object:  Database [patstat2016b]    Script Date: 12/02/2016 12:00:00 ******/
CREATE DATABASE [patstat2016b] ON  PRIMARY 
( NAME = N'patstat2016b_dat', FILENAME = N'G:\mssql_dbs\patstat2016b\patstat2016bdat.mdf' , SIZE = 200000MB , MAXSIZE = UNLIMITED , FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'patstat2016b_log', FILENAME = N'G:\mssql_dbs\patstat2016b\patstat2016blog.ldf' , SIZE = 1000MB , MAXSIZE = UNLIMITED , FILEGROWTH = 15360KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'patstat2016b', @new_cmptlevel=100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [patstat2016b].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [patstat2016b] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [patstat2016b] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [patstat2016b] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [patstat2016b] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [patstat2016b] SET ARITHABORT OFF 
GO
ALTER DATABASE [patstat2016b] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [patstat2016b] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [patstat2016b] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [patstat2016b] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [patstat2016b] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [patstat2016b] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [patstat2016b] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [patstat2016b] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [patstat2016b] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [patstat2016b] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [patstat2016b] SET  DISABLE_BROKER 
GO
ALTER DATABASE [patstat2016b] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [patstat2016b] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [patstat2016b] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [patstat2016b] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [patstat2016b] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [patstat2016b] SET  READ_WRITE 
GO
ALTER DATABASE [patstat2016b] SET RECOVERY FULL 
GO
ALTER DATABASE [patstat2016b] SET  MULTI_USER 
GO
ALTER DATABASE [patstat2016b] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [patstat2016b] SET DB_CHAINING OFF 