USE [master]
GO
/****** Object:  Database [patscape]    Script Date: 12/02/2016 12:00:00 ******/
CREATE DATABASE [patscape] ON  PRIMARY 
( NAME = N'patscape_dat', FILENAME = N'C:\mssql\dbs\patscape\patscapedat.mdf' , SIZE = 200000MB , MAXSIZE = UNLIMITED , FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'patscape_log', FILENAME = N'C:\mssql\dbs\patscape\patscapelog.ldf' , SIZE = 1000MB , MAXSIZE = UNLIMITED , FILEGROWTH = 15360KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'patscape', @new_cmptlevel=100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [patscape].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [patscape] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [patscape] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [patscape] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [patscape] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [patscape] SET ARITHABORT OFF 
GO
ALTER DATABASE [patscape] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [patscape] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [patscape] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [patscape] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [patscape] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [patscape] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [patscape] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [patscape] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [patscape] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [patscape] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [patscape] SET  DISABLE_BROKER 
GO
ALTER DATABASE [patscape] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [patscape] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [patscape] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [patscape] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [patscape] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [patscape] SET  READ_WRITE 
GO
ALTER DATABASE [patscape] SET RECOVERY FULL 
GO
ALTER DATABASE [patscape] SET  MULTI_USER 
GO
ALTER DATABASE [patscape] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [patscape] SET DB_CHAINING OFF 